### ISSUE TITLE
zypper version comparison doesn't work in libvirt_setup/openSUSE_vagrant_setup.sh

### ISSUE THREAD

**Issue by rdannert** [sigsteve/vagrant-caasp#38]
$ cat zypper-version
#!/bin/bash

#zypper_version=($(zypper -V))
zypper_version='1.14.27'
if [[ ${zypper_version[1]} < '1.14.4' ]]
then
    echo "<"
else
    echo ">"
fi

$ ./zypper-version
<
which is wrong

this would work, but requires rpmdev-vercmp provided by rpmdevtools from openSUSE:Backports:SLE-15-SP1 repo

[...]
zypper_version=($(rpm -q --qf 'zypper-%{V}\n'  zypper))

#https://unix.stackexchange.com/questions/163702/bash-script-to-verify-that-an-rpm-is-at-least-at-a-given-version
rpmdev-vercmp $zypper_version  'zypper-1.14.4'
if [[ $? == 11 ]] 
then
    zypper --no-gpg-checks in -y https://releases.hashicorp.com/vagrant/2.2.5/vagrant_2.2.5_x86_64.rpm
[...]

as /usr/bin/rpmdev-vercmp is a Python script, you could simply copy it to /usr/local/bin/

**Comment by SweBarre** [comment]
Hi,
I don't really understand the problem here but

> #zypper_version=($(zypper -V))
> zypper_version='1.14.27'
> if [[ ${zypper_version[1]} < '1.14.4' ]]

This won't work,
The row you commented out `zypper_version=($(zypper -V))` would result in an array, så `${zypper_version[0]` would contain the word *zypper* and `${zypper_version[1]}` would contain the version.
When you just put the version in the zypper_version variable like this `zypper_version='1.14.27` then the the `${zypper_version[1]}' wouldn't contain anything.
And the row `if [[ ${zypper_version[1]} < '1.14.4' ]]` would always compare a blank variable with 1.14.4.

You could test this yourself
```
$> zypper_version=($(zypper -V))
$> echo ${zypper_version[0]}
zypper
$> echo ${zypper_version[1]}
1.14.27
$> unset zypper_version
$> zypper_version='1.14.27
$> echo ${zypper_version[0]}
1.14.27
$> echo ${zypper_version[1]}

anyhow, the zypper_version test in libvirt_setup/openSUSE_vagrant_setup.sh seems to work for me, what is not working for you?

**Comment by rdannert** [comment]
on linux cmdline(using zypper version 1.14.27 from openSUSE15.1)

$  zypper -V
$ zypper_version=($(zypper -V))
$ echo ${zypper_version[1]}
1.14.27
$ if [[ ${zypper_version[1]} < '1.14.4' ]]; then echo smaller; else echo larger; fi
smaller

which is clearly wrong

rpmdev-vercmp needs the 'zypper-1.14.4' syntax, because the python algorithm requires it

**Comment by SweBarre** [comment]
Got it, now I understand the issue.
