### ISSUE TITLE
Enhancement ideas

### ISSUE THREAD

**Issue by ajaeger** [sigsteve/vagrant-caasp#54]
I'd like to use rook with ceph for storage and therefore need an extra disk on each worker node. Could this be easily added?

Also, these nodes have no subscriptions, an easy way to add them would be great so that we can install packages and updates.

Otherwise, great tool - love it! Thanks

**Comment by sigsteve** [comment]
> I'd like to use rook with ceph for storage and therefore need an extra disk on each worker node. 
> Could this be easily added?

The Vagrantfile currently has extra disks commented out.
You can uncomment the lv.storage lines and adjust the sizes as necessary.
When we get rook integrated, I plan to simplify this process.

Do you have any input around how we could make this "easy"?

> Also, these nodes have no subscriptions, an easy way to add them would be great so that we can
> install packages and updates.

Good idea. We are working on integrating RMT here as well.

**Comment by ne0777** [comment]
For the subscriptions:  We discussed this a bit and decided that the end user could register using SUSEConnect --url <RMT server>, or a SUSEConnect -r CAASP_REGISTRATION_CODE, etc on each node.  The thought being the box file might be more public at some point (like the SOC one on the vagrantup site).  Assuming people go get a valid trial code from us (or purchase a subscription) - this should work.

They would need to add the containers module and caasp product to each node (as is documented in the CaaSP documentation): 
sudo SUSEConnect -p sle-module-containers/15.1/x86_64 
sudo SUSEConnect -p caasp/4.0/x86_64 -r CAASP_REGISTRATION_CODE 

For rook - we do have the extra disk addition inside the Vagrantfile (commented out by default).  But we want to have options for devices too instead of just :file.  We intend to add some other deployment options to make this easy.  We have even talked about converting things to Ruby - versus using bash scripts (in /vagrant/deploy).

@sigsteve - do you want to elaborate on the 'extra disk' options?

**Comment by ne0777** [comment]
AH - ninja'd!
